version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
  - stage:
      - java:
          alias: jacoco-demo
          description: 针对 java 工程的编译打包任务，产出可运行镜像
          params:
            build_type: maven
            container_type: spring-boot
            target: ./target/jacoco-code-coverage-example-0.0.1-SNAPSHOT.jar
            workdir: ${git-checkout}
          caches:
            - path: /root/.m2/repository
  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          params:
            dice_yml: ${git-checkout}/erda.yml
            image:
              java-demo: ${jacoco-demo:OUTPUT:image}
  - stage:
      - dice:
          alias: erda
          description: 用于 erda 平台部署应用服务
          params:
            release_id: ${release:OUTPUT:releaseID}
